---
<%
  kitchen_driver_quick = 'docker'
  kitchen_driver_default = 'vagrant'
  
  if ENV['KITCHEN_DRIVER']
    kitchen_driver = ENV['KITCHEN_DRIVER']
  else
    kitchen_driver = kitchen_driver_default
  end 
  puts "----> driver_plugin = #{kitchen_driver.to_s}"
%>

driver:
  name: <%= kitchen_driver %>
<% if kitchen_driver == 'docker' %>
  binary: docker
  use_sudo: false
  privileged: true
<% end %>

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
<% if kitchen_driver == 'docker' %>
    driver_config:
      dockerfile: test/Dockerfile
      platform: centos      
<% end %>
  - name: ubuntu-14.04

suites:
  - name: default-latest
    run_list:
      - recipe[karaf_test::install]
    attributes:
      karaf_test:
        version: '4.0.4'

  - name: default-3
    run_list:
      - recipe[karaf_test::install]
    attributes:
      karaf_test:
        version: '3.0.3'

  - name: remove
    run_list: 
      - recipe[karaf_test::remove]

  - name: install-remove
    run_list: 
      - recipe[karaf_test::install]
      - recipe[karaf_test::remove]


  - name: slow-cloud
    run_list:
      - recipe[karaf_test::install]
    attributes:
      karaf_test:
        version: '3.0.3'
    driver:
      customize:
        cpuexecutioncap: 25
    excludes:
      - ubuntu-14.04
